# Security Configuration Template
security:
  # Input validation settings
  input_validation:
    enabled: true
    max_file_size_mb: 1000
    allowed_file_types: [".h5", ".csv", ".txt", ".json", ".yaml"]
    blocked_patterns: ["../", "eval(", "exec(", "__import__"]
  
  # Authentication settings
  authentication:
    require_api_key: true
    api_key_env_var: "SPATIAL_GFM_API_KEY"
    session_timeout_minutes: 60
  
  # Data protection
  data_protection:
    encrypt_at_rest: true
    require_https: true
    audit_data_access: true
  
  # Network security
  network:
    allowed_hosts: ["localhost", "127.0.0.1"]
    cors_enabled: false
    rate_limiting: true
    max_requests_per_minute: 100
  
  # Container security
  container:
    run_as_non_root: true
    read_only_filesystem: true
    no_new_privileges: true
